# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #878889

background #1E1F1D
foreground #E8EAEB

color0 #494B47
color1 #35581F
color2 #232358
color3 #2C7373
color4 #366E8F
color5 #3C619E
color6 #4C90C7
color7 #D6D9DB
color8 #969899
color9 #35581F
color10 #232358
color11 #2C7373
color12 #366E8F
color13 #3C619E
color14 #4C90C7
color15 #D6D9DB

mark1_foreground #3D89C7
mark2_foreground #ABC8DB
mark3_foreground #3D89C7
