# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #7F91CD

background #00000B
foreground #DFE9F6

color0 #00000D
color1 #8C97A3
color2 #8C97A3
color3 #C9D8EA
color4 #C9D8EA
color5 #8C97A3
color6 #C9D8EA
color7 #C9D8EA
color8 #8C97A3
color9 #8C97A3
color10 #8C97A3
color11 #C9D8EA
color12 #C9D8EA
color13 #8C97A3
color14 #C9D8EA
color15 #C9D8EA

mark1_foreground #C9D8EA
mark2_foreground #C9D8EA
mark3_foreground #C9D8EA
