# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #878889

background #1E1F1D
foreground #E8EAEB

color0 #494B47
color1 #969899
color2 #969899
color3 #D6D9DB
color4 #D6D9DB
color5 #969899
color6 #D6D9DB
color7 #D6D9DB
color8 #969899
color9 #969899
color10 #969899
color11 #D6D9DB
color12 #D6D9DB
color13 #969899
color14 #D6D9DB
color15 #D6D9DB

mark1_foreground #D6D9DB
mark2_foreground #D6D9DB
mark3_foreground #D6D9DB
