return {
  background = "{{background}}",
  foreground = "{{foreground}}",
  cursor = "{{cursor}}",
  color0 = "{{color0}}",
  color1 = "{{color8}}",
  color2 = "{{color8}}",
  color3 = "{{color7}}",
  color4 = "{{color7}}",
  color5 = "{{color8}}",
  color6 = "{{color7}}",
  color7 = "{{color7}}",
  color8 = "{{color8}}",
  color9 = "{{color8}}",
  color10 = "{{color8}}",
  color11 = "{{color7}}",
  color12 = "{{color7}}",
  color13 = "{{color8}}",
  color14 = "{{color7}}",
  color15 = "{{color15}}",
}
