# wallust v3.3
#
# You can copy this file to ~/dotfiles/wallust/wallust.toml (keep in mind is a sample config)

# SIMPLE TUTORIAL, or `man wallust.5`:
# https://explosion-mental.codeberg.page/wallust/
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml

# Global section - values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "fastresize"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lch"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "dark"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
check_contrast = true

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
# Keep monochrome wallpapers monochrome instead of pushing blue/green accents.
# saturation = 60

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/dotfiles/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ¡ If either one is a directory, then both SHOULD be one. !
# zathura = { template = 'zathura', target = '~/dotfiles/zathura/zathurarc' }

obsidian = { template = 'wallust-basic.css', target = '~/Documents/Vault/.obsidian/snippets/wallust-basic.css' }
waybar = { template = 'colors-wallust.css', target = '~/dotfiles/waybar/colors-wallust.css' }
kitty = { template = 'kitty.conf', target = '~/dotfiles/kitty/colors.conf' }
ghostty = { template = 'ghostty.conf', target = '~/.config/ghostty/colors.conf' }
neovim_vim = { template = 'colors_neopywal.vim', target = '~/.cache/wal/colors-wal.vim' }
neovim_lua = { template = 'nvim.lua', target = '~/.cache/wal/wallust.nvim.lua' }
rofi = { template = 'colors-rofi.rasi', target = '~/dotfiles/rofi/colors.rasi' }
nemo = { template = 'nemo.css', target = '~/.config/gtk-3.0/nemo.css' }
swaync = { template = 'swaync.css.tmpl', target = '~/.config/swaync/style.css' }
hyprland = { template = 'hyprland-colors.conf', target = '~/.config/hypr/wallust-colors.conf' }
hyprlock = { template = 'hyprlock-colors.conf', target = '~/.config/hypr/wallust-hyprlock.conf' }
tmux = { template = 'tmux.conf', target = '~/.config/tmux/wallust.conf' }
yazi = { template = 'yazi.toml', target = '~/.config/yazi/theme.toml' }
spotify_player = { template = 'spotify-player-theme.toml', target = '~/dotfiles/spotify-player/theme.toml' }
flameshot = { template = 'flameshot.ini', target = '~/dotfiles/flameshot/flameshot.ini' }
gtk3 = { template = 'gtk-colors.css', target = '~/.config/gtk-3.0/colors.css' }
gtk4 = { template = 'gtk-colors.css', target = '~/.config/gtk-4.0/colors.css' }
